version: '3'

services:
  app:
    image: remla23-team06/app:latest
    ports:
      - 8080:8080
    environment:
      - MODEL_SERVICE_URL=http://model-service:8000 
    depends_on:
      - model-service

  model-service:
    image: remla23-team06/model-service:latest # Option 1
    build:
      context: ./model-service # Option 2
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: python3 model_server.py
    depends_on:
      - model-training

  model-training:
    image: remla23-team06/model-training:latest