version: '3'

services:
  app:
    image: ghcr.io/remla23-team06/app:latest
    ports:
      - 8080:8080
    environment:
      - MODEL_SERVICE_URL=http://model-service:8000
    depends_on:
      - model-service

  model-service:
    image: ghcr.io/remla23-team06/model-service:latest
    ports:
      - 8080:8080
    depends_on:
      - model-training

  model-training:
    image: ghcr.io/remla23-team06/model-training:latest
