{
 "title": "app dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Ratio validations / predictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(validations_total{sender=\"without-emojis\"}) / sum(predictions_total{sender=\"without-emojis\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(validations_total{sender=\"with-emojis\"}) / sum(predictions_total{sender=\"with-emojis\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 * sum(validations_total{is_correct=\"False\"}) / sum(predictions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * sum(validations_total{is_correct=\"True\"}) / sum(predictions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sentiment Over Time",
   "type": "timeseries",
   "description": "Positive vs Negative sentiment count over time ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (is_correct)(rate(validations_total{is_correct=\"True\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (is_correct)(rate(validations_total{is_correct=\"False\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (is_correct)(validations_total{is_correct=\"True\"})\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (is_correct)(validations_total{is_correct=\"False\"})\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}