name: Build service stack
on:
    push:
        tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: Registry Login (ghcr.io)
              run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
            - name: Build Docker Services
              run: docker compose up --no-start --pull always --build
                  
                  
            

